import { BaseMessage } from '@langchain/core/messages';
import { Annotation } from '@langchain/langgraph';

/**
 * The State of the Multi-Agent workflow.
 * This object is passed between nodes (agents).
 */
export const AgentState = Annotation.Root({
  // The overall goal/prompt from the user
  goal: Annotation<string>({
    reducer: (x, y) => y ?? x,
    default: () => '',
  }),
  // History of messages between the system and agents
  messages: Annotation<BaseMessage[]>({
    reducer: (x, y) => x.concat(y),
    default: () => [],
  }),
  // The plan generated by the manager
  plan: Annotation<string[]>({
    reducer: (x, y) => y ?? x,
    default: () => [],
  }),
  // Current active step in the plan
  currentStep: Annotation<string>({
    reducer: (x, y) => y ?? x,
    default: () => '',
  }),
  // Files created or modified during this run
  touchedFiles: Annotation<string[]>({
    reducer: (x, y) => {
      const unique = new Set([...x, ...y]);
      return Array.from(unique);
    },
    default: () => [],
  }),
  testFailures: Annotation<number>({
    reducer: (x, y) => y ?? x,
    default: () => 0,
  }),
  // Error message from the test execution
  testError: Annotation<string>({
    reducer: (x, y) => y ?? x,
    default: () => '',
  }),
  // Final summary of the execution
  summary: Annotation<string>({
    reducer: (x, y) => y ?? x,
    default: () => '',
  }),
});
